// examples/angular-example/src/app/components/view-win/view-win.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import ViewWin from 'view-win'

@Component({
  selector: 'app-view-win',
  templateUrl: './view-win.component.html',
  styleUrls: ['./view-win.component.scss']
})
export class ViewWinComponent {
  list = ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'rmListener', 'JQuery', 'Angular', 'React', 'Vue', 'Nodejs', 'npm', 'nrm', 'nvm']
  viewWin!: any
  @ViewChild('eleRef')
  eleRef!: ElementRef;
  constructor() {
    
  }
  ngOnInit(): void {
    this.init()
  }
  // 初始化
  init() {
    setTimeout(() => {
      console.log(this.eleRef);
      this.viewWin = new ViewWin({
        target: this.eleRef.nativeElement,
        direction: 'x',
        vmid: true
      })
    });
  }
  // 移除事件
  handleRemove() {
    this.viewWin.rmEvent()
  }
}

<ul id="list" #eleRef>
  <li
    *ngFor="let item of list"
    [class.rmListener]="item === 'rmListener'"
    (click)="item === 'rmListener' && handleRemove()"
  >
    {{ item }}
  </li>
</ul>

// examples/vue-example/src/components/view-win.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import ViewWin from 'view-win'

const ele = ref<HTMLElement>()
const list = ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'rmListener', 'JQuery', 'Angular', 'React', 'Vue', 'Nodejs', 'npm', 'nrm', 'nvm']
const viewWin = ref()
onMounted(() => {
  viewWin.value = new ViewWin({
    target: ele.value,
    direction: 'x',
    vmid: true
  })
})

const handleRemove = () => {
  viewWin.value.rmEvent()
}

</script>

<template>
  <ul id="list" ref="ele">
    <li :class="{'rmListener': item === 'rmListener'}" v-for="item in list" @click="item === 'rmListener' && handleRemove()">{{ item }}</li>
  </ul>
</template>

<style scoped lang="scss">
ul#list {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  overflow: auto;
  display: flex;
  align-items: center;
  width: 400px;
  height: 50px;
  border-radius: 5px;
  box-shadow: 0 0px 10px 2px rgba(0, 0, 0, 8%);
  li {
    flex-shrink: 0;
    font-size: 20px;
    cursor: pointer;
    &:not(:last-child) {
      margin-right: 20px;
    }
  }
}
</style>
